name: Build package

on:
  push:
    branches: [ master ]

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}} >> .npmrc
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
